services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: groven
      POSTGRES_PASSWORD: groven
      POSTGRES_DB: groven_iq
    volumes:
      - postgres_test_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U groven -d groven_iq']
      interval: 5s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686' # Jaeger UI
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP ← your app sends traces here

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3000' # avoid clash with Next.js on 3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - jaeger

volumes:
  postgres_test_data:
