export const AUDIT_EVENTS = Object.freeze([
  'user.registered',
  'user.verified',
  'user.login',
  'user.logout',
  'org.created',
  'org.updated',
  'org.archived',
  'org.onboarding_skipped',
  'role.created',
  'role.updated',
  'role.deleted',
  'member.role_assigned',
  'member.role_revoked',
  'member.removed',
  'invitation.created',
  'meeting.created',
  'meeting.updated',
  'meeting.status_changed',
  'meeting.attendee_added',
  'meeting.attendee_removed',
  'vote.created',
  'vote.closed',
  'ballot.submitted',
  'minutes.created',
  'minutes.updated',
  'minutes.finalized',
  'minutes.correction_added',
  'minutes.exported',
  'system.cleanup',
] as const);

export type AuditEventName = (typeof AUDIT_EVENTS)[number];
