export const CONFIGURATIONS = {
  PASSWORD_MIN_LENGTH: 12,
  PASSWORD_COST_FACTOR: 11,
  OTP_LENGTH: 6,
  OTP_TTL_MS: 10 * 60 * 1000,
  OTP_RESEND_COOLDOWN_SEC: 60,
  ACCESS_TTL_SECONDS: 15 * 60,
  REFRESH_TTL_SECONDS: 7 * 24 * 60 * 60,
  REFRESH_COOKIE_NAME: 'refresh_token',
  REFRESH_RANDOM_BYTES: 32,
};
